version: '3.3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env # Add this line to mount the .env file
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scheduler_db
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5433:5432" # Changed from 5432:5432 to use port 5433 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=scheduler_db

volumes:
  postgres_data:
